### PR TITLE
Fix failing specs

### PR DESCRIPTION
**Pull request by nuclearsandwich**
This is just a precursor to additional changes, but it's a good idea to get CI passing.

/cc @gjtorikian @lachlanhardy @lynnwallenstein

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
As a head's up. Travis has been green because it's a [no-op](https://github.com/gjtorikian/publisher/blob/a4f941a49350dd05584eef62573faba5337d9669/script/cibuild#L24-L32) right now.

**Comment by nuclearsandwich** [comment]
The reason for CI being no-op'd is the lack of Ruby 2.2.3, if we get Ruby to 2.2.5 it looks like it would work across Mac OS, CI, Heroku, and my local Linux machine, which would be kickin' rad.

**Comment by lachlanhardy** [comment]
Heroku's current default is `2.2.4`, but it also supports `2.2.5` as long as specified. Or better yet, `2.3.1` :)

See https://devcenter.heroku.com/articles/ruby-support#ruby-versions

I agree getting onto any of those would be kickin' rad.

**Comment by nuclearsandwich** [comment]
shipit

**Pull request merged**
