### PR TITLE
Add support for cc_on_error query parameter

### PR DESCRIPTION
**Pull request by nuclearsandwich**
cc_on_error allows individual repositories to specify via query parameter specific teams or individuals who should be cc'd in all cases in the event of an error. I think a query parameter is the way to go
since it allows the value to be changed by anyone with admin access to the repository being published rather than someone with code or environment variable control access to publisher itself.

/cc @gjtorikian @lachlanhardy @lynnwallenstein

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
I have spec updates too but they're waiting on #8

**Comment by gjtorikian** [comment]
Cool. I like it.

**Comment by nuclearsandwich** [comment]
My plan for testing this:

- create a bogus repo with master and gh-pages branches
- add a publish task that goes :boom:
- set up the webhook for publisher
- push to master
- await my lovely new issue.

**Comment by nuclearsandwich** [comment]
Deploying this branch.

**Comment by nuclearsandwich** [comment]
publisher

Tested this both with and without a `cc_on_error` query parameter. One thing that's odd. The committers don't seem to be populated.

**Comment by nuclearsandwich** [comment]
Merged and master is deployed to Heroku.

**Pull request merged**
